import joinMonster from "join-monster";

export default {
  Query: {
    constants: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle constants resolver with sql queries generated by joinMonster
      });
    },
    initial_epoch: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle initial_epoch resolver with the sql query generated by joinMonster
      });
    },
    finalized_epochs: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle finalized_epochs resolver with the sql query generated by joinMonster
      });
    },
    current_epoch: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle current_epoch resolver with the sql query generated by joinMonster
      });
    },
    current_phase: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle current_phase resolver with the sql query generated by joinMonster
      });
    },
    output_state: (_, args, {}, info) => {
      joinMonster(info, args, (sql) => {
        // handle output_state resolver with the sql query generated by joinMonster
      });
    },
  },
};
